### ISSUE TITLE
Add dependency richDate

### ISSUE THREAD

**Issue by simen** [kmelve/sanity-plugin-podcast#2]
`richDate` is not a part of the default Sanity distro and should be added as a dependency here. It is provided by the npm-package `@sanity/rich-date-input` and should be in the package.json and also enabled by adding `"plugins": ["@sanity/rich-date-input"]` in sanity.json.

**Comment by simen** [comment]
Or maybe it should use the more light-weight `datetime` type, which _is_  part of the standard distro? 

https://www.sanity.io/docs/schema-types/datetime-type

That would of course probably involve updating the server too?

**Comment by simen** [comment]
… wait, there is a bug in the rich date plugin that prevents it from automatically adding its type to the schema. Will fix for next release.

**Comment by kmelve** [comment]
We'll use `datetime` for now. Fixed in 2afbef59de3e3ad67fd209ac88086f5989fef35b! Thanks for the heads up!
